"""add website health checks

Revision ID: 05c0ddcd7fe5
Revises: defd8f4c77fb
Create Date: 2026-09-10 16:36:19.003883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c0ddcd7fe5'
down_revision: Union[str, None] = 'defd8f4c77fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_health_checks',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='healthstatus', native_enum=False, length=20), nullable=False),
    sa.Column('checked_url', sa.String(length=2048), nullable=True),
    sa.Column('http_status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='healthstatus', native_enum=False, length=20), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('http_latency_ms', sa.Float(), nullable=True),
    sa.Column('dns_status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='healthstatus', native_enum=False, length=20), nullable=False),
    sa.Column('tls_status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='healthstatus', native_enum=False, length=20), nullable=False),
    sa.Column('tls_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tls_days_remaining', sa.Integer(), nullable=True),
    sa.Column('deployment_status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='healthstatus', native_enum=False, length=20), nullable=False),
    sa.Column('deployment_last_deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('form_status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='healthstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', name='uq_website_health_checks_business_id')
    )
    op.create_index(op.f('ix_website_health_checks_business_id'), 'website_health_checks', ['business_id'], unique=False)
    op.create_index(op.f('ix_website_health_checks_tenant_id'), 'website_health_checks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_health_checks_tenant_id'), table_name='website_health_checks')
    op.drop_index(op.f('ix_website_health_checks_business_id'), table_name='website_health_checks')
    op.drop_table('website_health_checks')
    # ### end Alembic commands ###
