"""initial domain model

Revision ID: c95f79055901
Revises: 
Create Date: 2026-08-25 21:11:14.581741

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c95f79055901'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vertical', sa.Enum('home_renovation', 'real_estate', 'clinic', 'agency', 'b2b_services', 'restaurant', 'ecommerce', 'hotel', 'other', name='businessvertical', native_enum=False, length=30), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', name='businessstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_tenant_id'), 'businesses', ['tenant_id'], unique=False)
    op.create_table('templates',
    sa.Column('kind', sa.Enum('website_block', 'workflow_pattern', name='templatekind', native_enum=False, length=20), nullable=False),
    sa.Column('vertical', sa.Enum('home_renovation', 'real_estate', 'clinic', 'agency', 'b2b_services', 'restaurant', 'ecommerce', 'hotel', 'other', name='businessvertical', native_enum=False, length=30), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_tenant_id'), 'templates', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('owner', 'operator', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('integrations',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('webhook', 'gmail', 'google_sheets', 'slack', 'hubspot', name='integrationprovider', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'connected', 'error', 'disconnected', name='integrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_business_id'), 'integrations', ['business_id'], unique=False)
    op.create_index(op.f('ix_integrations_tenant_id'), 'integrations', ['tenant_id'], unique=False)
    op.create_table('websites',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('deploy_target', sa.Enum('cloudflare', name='deploytarget', native_enum=False, length=20), nullable=False),
    sa.Column('deploy_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('draft', 'building', 'live', 'failed', name='websitestatus', native_enum=False, length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', name='uq_websites_business_id')
    )
    op.create_index(op.f('ix_websites_business_id'), 'websites', ['business_id'], unique=False)
    op.create_index(op.f('ix_websites_tenant_id'), 'websites', ['tenant_id'], unique=False)
    op.create_table('workflows',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'provisioning', 'active', 'inactive', 'error', name='workflowstatus', native_enum=False, length=20), nullable=False),
    sa.Column('n8n_workflow_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_business_id'), 'workflows', ['business_id'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_table('credentials',
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', name='uq_credentials_integration_id')
    )
    op.create_index(op.f('ix_credentials_integration_id'), 'credentials', ['integration_id'], unique=False)
    op.create_index(op.f('ix_credentials_tenant_id'), 'credentials', ['tenant_id'], unique=False)
    op.create_table('executions',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('website_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('workflow_run', 'website_build', name='executiontype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='executionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_execution_id', sa.String(length=200), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(type = 'workflow_run' AND workflow_id IS NOT NULL AND website_id IS NULL) OR (type = 'website_build' AND website_id IS NOT NULL AND workflow_id IS NULL)", name='ck_executions_target_matches_type'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_business_id'), 'executions', ['business_id'], unique=False)
    op.create_index(op.f('ix_executions_tenant_id'), 'executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_executions_website_id'), 'executions', ['website_id'], unique=False)
    op.create_index(op.f('ix_executions_workflow_id'), 'executions', ['workflow_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Enum('ai', 'human', name='configorigin', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'published', name='workflowversionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_workflow_versions_workflow_version')
    )
    op.create_index(op.f('ix_workflow_versions_tenant_id'), 'workflow_versions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_tenant_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_executions_workflow_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_website_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_tenant_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_business_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_credentials_tenant_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_integration_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_business_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_websites_tenant_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_business_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_integrations_tenant_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_business_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_tenant_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_businesses_tenant_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('tenants')
    # ### end Alembic commands ###
