"""LocalStorageProvider — saves uploaded files to a local directory on
disk, served back over HTTP via a static file mount (see app.main's
StaticFiles mount at /uploads). Dev/single-instance only — Phase 3
explicitly says not to introduce cloud infrastructure before a real need
justifies it; a future S3StorageProvider/R2StorageProvider implements the
same StorageProvider interface once one does.
"""

import re
from pathlib import Path

from app.storage.provider import StorageProvider, StoredFile

# Storage keys are always generated by generate_storage_key below — never
# taken from user input directly — but this guard stays as defense in
# depth against a key reaching _resolve some other way.
_SAFE_KEY_PATTERN = re.compile(r"^[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9]{1,10})?$")


class LocalStorageProvider(StorageProvider):
    def __init__(self, *, root_dir: Path) -> None:
        self._root_dir = root_dir
        self._root_dir.mkdir(parents=True, exist_ok=True)

    def save(self, *, storage_key: str, content: bytes) -> StoredFile:
        path = self._resolve(storage_key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        return StoredFile(storage_key=storage_key)

    def delete(self, storage_key: str) -> None:
        self._resolve(storage_key).unlink(missing_ok=True)

    def load(self, storage_key: str) -> bytes:
        return self._resolve(storage_key).read_bytes()

    def url_path(self, storage_key: str) -> str:
        return f"/uploads/{storage_key}"

    def _resolve(self, storage_key: str) -> Path:
        if not _SAFE_KEY_PATTERN.match(storage_key):
            raise ValueError(f"unsafe storage key: {storage_key!r}")
        resolved = (self._root_dir / storage_key).resolve()
        if self._root_dir.resolve() not in resolved.parents:
            raise ValueError(f"storage key escapes storage root: {storage_key!r}")
        return resolved
