"""CloudflareR2StorageProvider — production persistent storage (P2.1).

Railway's own local filesystem is ephemeral: a redeploy silently destroys
whatever LocalStorageProvider (app.storage.local) wrote — including
GenerativeWebsiteArtifact source archives and Visual QA screenshots, both
customer-facing artifacts that must survive a redeploy. R2 is Cloudflare's
S3-compatible object storage, a natural fit given this repository already
deploys through Cloudflare (Pages/Workers — see app.publishing.cloudflare)
and needs no new vendor relationship.

boto3 (pinned S3-compatible client, `endpoint_url` pointed at R2) is used
instead of hand-rolling AWS SigV4 request signing over httpx — signing is
a correctness-sensitive algorithm this codebase has no existing
implementation of, and getting it subtly wrong is a real risk not worth
taking for one provider (see pyproject.toml's own note on this choice).

Unlike LocalStorageProvider's `url_path` (always root-relative — the
caller adds its own host), this provider returns an ABSOLUTE public URL
(`r2_public_base_url`, a real configured value, never guessed) — R2 serves
objects from its own public bucket domain, not from this API's own host.
See app.storage.provider.StorageProvider.url_path's own docstring for why
returning an absolute URL here is not a contract violation: the provider
genuinely knows its own public hostname because it was configured with
it, never inferred.
"""

import re

from botocore.client import Config
from botocore.exceptions import ClientError

from app.storage.provider import StorageProvider, StoredFile

# Same key-shape guard app.storage.local.LocalStorageProvider applies —
# duplicated, not imported, since that's a private helper of a sibling
# module (see app.creative.frontend_engine.visual_qa's own docstring for
# why this codebase prefers a small duplicated helper over reaching into
# another module's underscore-prefixed internals). Storage keys are always
# generated by app.storage.keys.generate_storage_key, never taken from
# user input directly, but this stays as defense in depth.
_SAFE_KEY_PATTERN = re.compile(r"^[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9]{1,10})?$")


def _validate_key(storage_key: str) -> None:
    if not _SAFE_KEY_PATTERN.match(storage_key):
        raise ValueError(f"unsafe storage key: {storage_key!r}")


class CloudflareR2StorageProvider(StorageProvider):
    def __init__(
        self,
        *,
        account_id: str,
        access_key_id: str,
        secret_access_key: str,
        bucket_name: str,
        public_base_url: str,
        client=None,
    ) -> None:
        self._bucket = bucket_name
        self._public_base_url = public_base_url.rstrip("/")
        if client is not None:
            self._client = client
        else:
            import boto3

            self._client = boto3.client(
                "s3",
                endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
                aws_access_key_id=access_key_id,
                aws_secret_access_key=secret_access_key,
                # R2 has no regions of its own — "auto" is Cloudflare's
                # own documented value for the S3-compatible API.
                region_name="auto",
                config=Config(signature_version="s3v4"),
            )

    def save(self, *, storage_key: str, content: bytes) -> StoredFile:
        _validate_key(storage_key)
        self._client.put_object(Bucket=self._bucket, Key=storage_key, Body=content)
        return StoredFile(storage_key=storage_key)

    def delete(self, storage_key: str) -> None:
        _validate_key(storage_key)
        try:
            self._client.delete_object(Bucket=self._bucket, Key=storage_key)
        except ClientError:
            # Idempotent per the StorageProvider contract — a delete of an
            # already-gone (or never-existed) key must not raise.
            pass

    def load(self, storage_key: str) -> bytes:
        _validate_key(storage_key)
        response = self._client.get_object(Bucket=self._bucket, Key=storage_key)
        return response["Body"].read()

    def url_path(self, storage_key: str) -> str:
        return f"{self._public_base_url}/{storage_key}"
